# Generated by Django 4.0.5 on 2022-06-14 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
